name: Build and Publish to gh-pages Branch

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node 
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: |
          **/node_modules
        key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run build
      env:
         CI: ""
         
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@4.1.4
      with:
          branch: gh-pages
          folder: build  
